// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHcwRSshcTbYrBk-XJNrm6U2dRTXhBJw',
    appId: '1:222538830642:ios:1a76faec5fb6579c85fd2b',
    messagingSenderId: '222538830642',
    projectId: 'medilink-cc25b',
    databaseURL: 'https://medilink-cc25b-default-rtdb.firebaseio.com',
    storageBucket: 'medilink-cc25b.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHcwRSshcTbYrBk-XJNrm6U2dRTXhBJw',
    appId: '1:222538830642:ios:1a76faec5fb6579c85fd2b',
    messagingSenderId: '222538830642',
    projectId: 'medilink-cc25b',
    databaseURL: 'https://medilink-cc25b-default-rtdb.firebaseio.com',
    storageBucket: 'medilink-cc25b.firebasestorage.app',
    iosBundleId: 'com.example.medilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTQ4218OhFyvDsPsOdnfbIJXayFey6pF8',
    appId: '1:222538830642:web:bd1c16876cfdf3e785fd2b',
    messagingSenderId: '222538830642',
    projectId: 'medilink-cc25b',
    authDomain: 'medilink-cc25b.firebaseapp.com',
    databaseURL: 'https://medilink-cc25b-default-rtdb.firebaseio.com',
    storageBucket: 'medilink-cc25b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQ4218OhFyvDsPsOdnfbIJXayFey6pF8',
    appId: '1:222538830642:web:7211124b7a05d62785fd2b',
    messagingSenderId: '222538830642',
    projectId: 'medilink-cc25b',
    authDomain: 'medilink-cc25b.firebaseapp.com',
    databaseURL: 'https://medilink-cc25b-default-rtdb.firebaseio.com',
    storageBucket: 'medilink-cc25b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdNbJsyI6lnPRUVDi3UoUaBMlNg6RZUgA',
    appId: '1:222538830642:android:39c5a6884635933c85fd2b',
    messagingSenderId: '222538830642',
    projectId: 'medilink-cc25b',
    databaseURL: 'https://medilink-cc25b-default-rtdb.firebaseio.com',
    storageBucket: 'medilink-cc25b.firebasestorage.app',
  );

}